### ISSUE TITLE
Image quality: Picture kinda nervous

### ISSUE THREAD

**Issue by egrath** [mist-devel/beeb#2]
**Issue:**
The core produced image is kinda nervous which makes it hard to look at it for longer time (like coding in BBC BASIC). The problem persists, no matter what screen mode is selected.

As it's a relatively subtle annoyance, some may possibly not even notice it. To see it, just start the core and stay in Mode 7, then take a exact look at the pixels of the letters, they slightly wobble around in various directions. 

To make sure it's not a issue on my side:
- Tested different (high quality shielded) cables with the following settings: VGA => scandoubler_disable=0, SCART => scandoubler_disable=0
- Tested different LCD Displays and TVs. The "better" the display is (speak the less image enhancements it has), the more visible the issue is. Seems like some TVs try to compensate such slight wobbling effects on their SCART input. 
- The setup works well with many other cores (Minimig-AGA, C64, ...)

**Expected behavior:**
Stable and calm image

**Comment by gyurco** [comment]
nervous -> it's called interlaced :)

**Comment by egrath** [comment]
Thanks for the hint with interlacing, but isn’t the scandoubler supposed to compensate for this? Or do i misunderstand the whole thingy? 🙂

/edit: Nevermind, i've read into this... scandoubling isn't the same as deinterlacing (as i thought previously) and in addition, the beeb only outputs interlaced formats. So it works as supposed. My fault, sorry.
